# ZK Core Example Configuration

# Main configuration
notes_dir: "~/notes"  # Path to your notes directory
socket_path: "/tmp/obsidian.sock"  # Path to Neovim socket for editor integration

# Index configuration
zk_index:
  index_file: "index.json"  # Name of the index file
  exclude_patterns: [".git", ".obsidian", "node_modules"]  # Directories to exclude
  excluded_files: ["README.md"]  # Files to exclude from indexing

# Query configuration
query:
  default_index: "index.json"
  default_fields: ["filename", "title", "tags"]

# FZF interface configuration
fzf_interface:
  bat_command: "bat"  # Command for preview
  fzf_args: "--height=80% --layout=reverse --info=inline"

# Working memory configuration
working_mem:
  template_path: "~/notes/templates/working_mem.md"
  editor: "nvim"
  tag: "working_mem"

# Backlinks configuration
backlinks:
  notes_dir: "~/notes"  # This is redundant with the global notes_dir, kept for backward compatibility
  bat_theme: "Dracula"  # Theme for bat preview

# Bibliography configuration
bibview:
  bibliography_json: "~/Dropbox/bibliography.json"  # Path to bibliography JSON
  dropbox_bibliography_json: "~/Dropbox/bibliography.json"  # Optional additional bibliography output path
  bibhist: "~/.bibhist"  # Path to history file
  library: "~/biblib"  # Path to bibliography library
  notes_dir_for_zk: "~/notes"  # Path for Zettelkasten notes
  bat_theme: "Dracula"  # Theme for bat preview
  bibview_open_doc_script: "~/bin/open_doc.sh"  # Script for opening documents
  llm_path: "~/bin/llm"  # Path to LLM script
  zk_script: "~/bin/zk"  # Path to zk script
  link_zathura_tmp_script: "~/bin/link_zathura.sh"  # Script for linking Zathura
  obsidian_socket: "/tmp/obsidiansocket"  # Socket for Obsidian


# Wikilink generator configuration
wikilink:
  # Profile for person notes
  person:
    filter_tags: ["person"]
    search_fields: ["filename", "aliases", "givenName", "familyName"]
    display_fields: ["filename", "aliases", "givenName", "familyName"]
    alias_fields: ["aliases", "givenName"]
    preview:
      command: "bat"
      window: "wrap:50%:<40(up)"
    fzf:
      delimiter: "::"
      tiebreak: "begin,index"
  
  # Profile for book notes
  book:
    filter_tags: ["book"]
    search_fields: ["filename", "title", "author"]
    display_fields: ["title", "author", "filename"]
    alias_fields: ["title"]
  
  # Profile for concept notes
  concept:
    filter_tags: ["concept"]
    search_fields: ["filename", "title", "description"]
    alias_fields: ["title"]
  
  # Default profile (searches all notes)
  default:
    filter_tags: []  # No tag filter - all notes
    search_fields: ["filename", "title", "tags"]
    alias_fields: ["title", "aliases"]

# Global logging configuration
logging:
  level: "INFO"  # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  file: "~/.zk_core.log"  # Log file path

# Filename configuration
filename:
  format: "%Y%m%d{random:3}"  # Format for generated filenames; supports strftime and {random:N}
  extension: ".md"  # File extension for generated files