#!/usr/bin/env bash

CONFIG_FILE="$HOME/.config/zk_scripts/config.yaml"

SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"
source "$SCRIPT_DIR/config_loader.sh"

load_config "$CONFIG_FILE" "personSearch" # Call load_config with config file and script section name

cd "$NOTES_DIR" || exit

# Run fzf and process the output
selection=$(
    "$PY_ZK" --index-file "index.json" --filter-tag person --fields filename aliases givenName familyName --color always \
            | fzf \
        --bind "ctrl-e:execute[nvim $NOTES_DIR/{1}.md]" \
        --bind "one:accept" \
        --delimiter="::" \
        --with-nth=2,3,4 \
        --tiebreak=begin,index \
        --info=right \
        --ellipsis= --preview-label='' \
        --preview="$BAT_COMMAND $NOTES_DIR/{1}.md"\
        --preview-window 'wrap:50%:<40(up)' \
        --ansi
)


# If no selection, exit
[ -z "$selection" ] && exit

transform=$(echo "$selection" | awk -F :: '{print $1}' | "$PY_ZK" --index-file index.json --stdin --output-format plain --format-string '[[{filename}|{givenName}]]' --separator='')

# Send the processed output to the active tmux pane
tmux send-keys "$transform"


