#!/usr/bin/env bash

CONFIG_FILE="$HOME/.config/zk_scripts/config.yaml"

SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"
source "$SCRIPT_DIR/config_loader.sh"

load_config "$CONFIG_FILE" "zk_fzf" # Call load_config with config file and script section name

# # Add mybin to PATH (if it exists and is not already there)
# if [[ -d "$MYBIN_DIR" && ! :"$PATH": =~ :"$MYBIN_DIR": ]]; then
#     PATH="$PATH:$MYBIN_DIR"
# fi

cd "$NOTES_DIR" || exit

TEMPLINK=$(mktemp)

"$PY_ZK" list --mode notes -i "$INDEX_FILE" --format-string '[[{filename}|{title}]]' > ~/Documents/notelist.md &

"$ZK_INDEX_SCRIPT" -v
"$PY_ZK" list --mode notes -i "$INDEX_FILE" --color always \
| fzf \
    --tiebreak=begin,index \
    --delimiter='::' \
    --info=right \
    --ellipsis= \
    --preview-label='' \
    --multi \
    --bind "Enter:execute[nvim --server /tmp/obsidian.sock --remote $NOTES_DIR/{+1}.md]+abort" \
    --bind "alt-a:execute[\"$ZK_INDEX_SCRIPT\"]+reload:(\"$PY_ZK\" list --mode notes -i \"$INDEX_FILE\" --color always )" \
    --bind "alt-w:execute[echo {+1} | sed 's/ /\n/g' | $PY_ZK list --mode notes -i $NOTES_DIR/index.json --stdin --format-string '- [[{filename}|{title}]]' --separator='' >> workingMem.md ]+reload:(\"$PY_ZK\" list --mode notes -i \"$INDEX_FILE\" --color always )" \
    --bind "alt-o:execute[\"$ZK_INDEX_SCRIPT\"]+reload:(\"$PY_ZK\" list --mode orphans -i \"$INDEX_FILE\" --color always )" \
    --bind "alt-O:execute[\"$ZK_INDEX_SCRIPT\"]+reload:(\"$PY_ZK\" list --mode untagged-orphans -i \"$INDEX_FILE\" --color always )" \
    --bind "alt-e:reload:(\"$PY_ZK\" list --mode notes -i \"$INDEX_FILE\" --color always --exclude-tag literature_note --exclude-tag person --exclude-tag task --exclude-tag diary --exclude-tag journal  )" \
    --bind "alt-y:execute[echo {+1} | sed 's/ /\n/g' | $PY_ZK list --mode notes -i $NOTES_DIR/index.json --stdin --format-string '[[{filename}|{title}]]' --separator='' > $TEMPLINK ]+abort" \
    --bind "ctrl-e:execute[nvim {+1}.md ; \"$ZK_INDEX_SCRIPT\"]+reload:(\"$PY_ZK\" list --mode notes -i \"$INDEX_FILE\" --color always )" \
    --bind "ctrl-alt-r:execute[rm {+1}.md]+reload:(\"$PY_ZK\" list --mode notes -i \"$INDEX_FILE\" --color always )" \
    --bind "ctrl-alt-d:execute[nvim \"$NOTES_DIR/$NOTES_DIARY_SUBDIR/$(date '+%Y-%m-%d' -d tomorrow).md\";]" \
    --bind "alt-9:reload[\"$PY_ZK\" list --mode unique-tags -i \"$INDEX_FILE\"  --color always]+clear-query" \
    --bind "alt-1:reload[rg -l {1} | sed 's/\.md$//g' | \"$PY_ZK\" list --mode notes -i \"$INDEX_FILE\" --color always --stdin]+clear-query" \
    --bind "alt-8:reload[\"$PY_ZK\" list --mode notes -i \"$INDEX_FILE\" --filter-tag {1}  --color always]+clear-query" \
    --bind "?:reload(\"$PY_ZK\" info -i \"$INDEX_FILE\" )" \
    --bind "alt-?:toggle-preview" \
    --bind "alt-j:reload[\"$PY_ZK\" list --mode notes -i \"$INDEX_FILE\" --filter-tag diary  --color always]" \
    --bind "alt-g:execute[echo {+1} | sed 's/ /\n/g' | \"$PY_ZK\" list --stdin -i \"$INDEX_FILE\" --format-string '- [[{filename}|{title}]]' >> {1}.md ]+clear-selection" \
    --bind "alt-b:reload[\"$PY_ZK\" list --mode notes -i \"$INDEX_FILE\" --filter-tag literature_note  --color always]" \
    --bind "ctrl-s:reload[rg '^' --sortr modified --field-match-separator='::' --color=always --type md -n | sed 's/\.md//' ]" \
    --preview="echo \"Backlinks:\";  rg '\\['{1} -l ; bat --theme=\"$BAT_THEME\" --color=always --decorations=never {1}.md -H {2} 2> /dev/null || bat {1}.md " \
    --preview-window 'wrap:50%:<50(up)' \
    --color 16 \
    --ansi



if [[ -e $TEMPLINK ]]
then
        link=$(cat "$TEMPLINK")
        tmux send-keys -l "$link"
else
        exit
fi



